apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitlbee
  labels:
    app: bitlbee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitlbee
  template:
    metadata:
      labels:
        app: bitlbee
    spec:
      containers:
        - name: bitlbee
          image: docker.io/mbologna/docker-bitlbee:latest
          ports:
            - containerPort: 6667
          volumeMounts:
            - name: bitlbee-data
              mountPath: /var/lib/bitlbee

        - name: stunnel


      volumes:
        - name: bitlbee-data
          emptyDir: {}
