name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2
        with:
          dockerfile: ./Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docker-bitlbee:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/docker-bitlbee:latest
            ghcr.io/${{ github.repository_owner }}/docker-bitlbee:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/docker-bitlbee:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan Docker image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/docker-bitlbee:${{ github.sha }}
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
