name: CI

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/docker-ci.yml@6fdc07da84568ecd0267b47c2a3e135687e1a961 # main
    with:
      image_name: docker-bitlbee
      yamllint_paths: docker-compose.yml .github/workflows/
      enable_integration_test: true
      enable_release_drafter: true
      enable_grype: false
    secrets: inherit

  auto-release:
    if: github.event_name == 'schedule'
    needs: [docker]
    uses: mbologna/.github/.github/workflows/auto-release.yml@6fdc07da84568ecd0267b47c2a3e135687e1a961 # main
    with:
      strategy: docker
      image: docker.io/mbologna/docker-bitlbee
    secrets: inherit
