name: CI

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/docker-ci.yml@eb320780c9de8219fe831960e9c225c60b338bab # main
    with:
      image_name: docker-bitlbee
      yamllint_paths: docker-compose.yml .github/workflows/
      enable_integration_test: true
      enable_release_drafter: true
    secrets: inherit
